git:
  buildVersionsUrl: git@github.com/boxboat/build-versions.git
  credentials: git
  email: jenkins@boxboat.com
  remotePathRegex: github\.com/(.*)\.git$
  remoteUrlReplace: git@github.com/{{ path }}.git
registryMap:
  default:
    scheme: https
    host: dtr.boxboat.com
    credentials: registry
vaultMap:
  default:
    url: http://localhost:8200
    credentials: vault
