deployTargetMap:
  default: !!com.boxboat.jenkins.library.deployTarget.KubernetesDeployTarget
    contextName: boxboat
    credential: kubeconfig
git:
  buildVersionsUrl: git@github.com/boxboat/build-versions.git
  credential: git
  email: jenkins@boxboat.com
  remotePathRegex: github\.com/(.*)\.git$
  remoteUrlReplace: git@github.com/{{ path }}.git
notifications:
  failureProvider: default
  successProvider: default
  providerMap:
    default: !!com.boxboat.jenkins.library.notification.SlackNotificationProvider
      credential: slack-webhook-url
registryMap:
  default:
    scheme: https
    host: dtr.boxboat.com
    credential: registry
vaultMap:
  default:
    kvVersion: 1
    roleIdCredential: vault-role-id
    secretIdCredential: vault-secret-id
    tokenCredential: vault-token
    url: http://localhost:8200
